In [108]:
import numpy as np
#计算逆矩阵，并检查求解结果
A = np.mat("0 1 2;1 0 3;4 -3 8")
print("A\n",A)
inverse = np.linalg.inv(A)
print("Inverse of A\n",inverse)
print("Check\n", A*inverse)
#求解线性方程组
B = np.mat("1 -2 1;0 2 -8;-4 5 9")
print("B\n",B)
b = array([0,8,-9])
print("b\n",b)
x = np.linalg.solve(B,b)
print("Solution",x)
print("Check\n",np.dot(B,x))
#求解特征值和特征向量
C = np.mat("3 -2;1 0")
print("C\n",C)
#求解特征值
print("Eigenvalues",np.linalg.eigvals(C))
eigenvalues,eigenvectors = np.linalg.eig(C)
print("First tuple of eig\n",eigenvectors)
print("Second tuple of eig\n",eigenvectors)
#使用dot函数验证求得结果的正确性，分别计算等式Ax=ax的左半部分和右半部分是否相等
for i in range(len(eigenvectors)):
    print("Left\n",np.dot(C,eigenvectors[:,i]))
    print("Right\n",eigenvectors[i]*eigenvectors[:,i])
    print("Done")
#奇异值分解
D =  np.mat("4 11 14;8 7 -2")
print("D\n",D)
U,sigma,V = np.linalg.svd(D,full_matrices=False)
print("U\n",U)
print("sigma\n",sigma)
print("V\n",V)
#广义逆矩阵
pseudoinv = np.linalg.pinv(D)
print("Pseudo inverse\n",pseudoinv)
#行列式
E = np.mat("3 4;5 6")
print("E\n",E)
print("Determainant\n",np.linalg.det(E))
#傅里叶变换


A
 [[ 0  1  2]
 [ 1  0  3]
 [ 4 -3  8]]
Inverse of A
 [[-4.5  7.  -1.5]
 [-2.   4.  -1. ]
 [ 1.5 -2.   0.5]]
Check
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
B
 [[ 1 -2  1]
 [ 0  2 -8]
 [-4  5  9]]
b
 [ 0  8 -9]
Solution [29. 16.  3.]
Check
 [[ 0.  8. -9.]]
C
 [[ 3 -2]
 [ 1  0]]
Eigenvalues [2. 1.]
First tuple of eig
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
Second tuple of eig
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
Left
 [[1.78885438]
 [0.89442719]]
Right
 [[1.11622777]]
Done
Left
 [[0.70710678]
 [0.70710678]]
Right
 [[0.81622777]]
Done
D
 [[ 4 11 14]
 [ 8  7 -2]]
U
 [[-0.9486833  -0.31622777]
 [-0.31622777  0.9486833 ]]
sigma
 [18.97366596  9.48683298]
V
 [[-0.33333333 -0.66666667 -0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]]
Pseudo inverse
 [[-0.00555556  0.07222222]
 [ 0.02222222  0.04444444]
 [ 0.05555556 -0.05555556]]
E
 [[3 4]
 [5 6]]
Determainant
 -2.0000000000000004


In [82]:
# import numpy as np
import sys
#c,v = np.loadtxt('data.csv',delimiter=',',usecols=(6,7),unpack=True)
#vwap = np.average(c,weights=v)
#print('vwap =', vwap)
#print(np.mean)
N = int(sys.argv[1])
weights = np.ones(N)/N
print(weight)

ValueError: invalid literal for int() with base 10: '-f'